# Generated by Django 4.1.3 on 2024-06-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/%Y/%m/%d/'),
        ),
    ]
