# Generated by Django 4.1.3 on 2024-06-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_artigo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artigo',
            name='leituras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artigo',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artigo',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
