# Generated by Django 4.1.3 on 2024-06-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_artigo_destaque_artigo_leituras_artigo_popular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='popular',
        ),
    ]
