# Generated by Django 4.1.3 on 2024-06-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_artigo_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='leituras',
        ),
    ]
